apiVersion: apps/v1
kind: Deployment
metadata:
  name: csr-approver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csr-approver
  template:
    metadata:
      labels:
        name: csr-approver
    spec:
      serviceAccountName: csr-approver
      containers:
        - name: csr-approver
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - csr-approver
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csr-approver"
