apiVersion: apps/v1
kind: Deployment
metadata:
  name: csr-approver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csr-approver
  template:
    metadata:
      labels:
        name: csr-approver
    spec:
      serviceAccountName: csr-approver
      tolerations:
        - effect: NoSchedule
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      containers:
        - name: csr-approver
          image: docker.io/jnummelin/csr-approver:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csr-approver"
