kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csr-approver
subjects:
- kind: ServiceAccount
  name: csr-approver
roleRef:
  kind: Role
  name: csr-approver
  apiGroup: rbac.authorization.k8s.io
