kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csr-approver
rules:
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approve
  verbs:
  - "*"
